---
title: "Proyecto de ley que fija Ley Marco de Cambio Climático" 
subtitle: "Reporte Congreso Virtual"
author: "Boletín: 13191-12"
output: html_document
---

> Fecha de ingreso: lunes 13 de enero de 2020\
> Estado: Primer trámite constitucional\
> Total participantes: 259 personas\


```{r load-packages, include = FALSE}
library(dplyr)
library(readr)
library(tidyverse)
library(knitr)
library(readxl)
library(janitor)
library(broom)
library(kableExtra)
```

```{r read-excel, include = FALSE}
votos <- read_excel("VOTOS + COMENTARIOS Cambio Climático.xlsx", 
    sheet = "VOTO GENERAL")

coments <- read_excel("VOTOS + COMENTARIOS Cambio Climático.xlsx", 
    sheet = "COMENTARIOS")
```


*** 


```{r recode-gen, include = FALSE}
votos <- votos %>%
  mutate(genero = case_when (
    genero == "1" ~ "Masculino",
    genero == "2" ~ "Femenino",
    genero == "-" ~ "Abstención"
  ))
```

```{r recode-vote, include = FALSE}
votos <- votos %>%
  mutate(vote = case_when (
    vote == "0" ~ "A favor",
    vote == "1" ~ "En contra",
    vote == "2" ~ "Abstención"
  ))
```


```{r freq-gen, include = FALSE}
votos %>%
  count(genero) %>%
  mutate(freq_gen = n / sum(n))
```

```{r freq-vote, include=FALSE}
freq_vote <- votos %>%
  count(vote) %>%
  mutate(percentage_voto = n / sum(n)*100)
```


### Votación General 
<br/>

#### Resultados Votación

```{r table-vote, echo=FALSE, fig.align='left'}
votos %>%
  tabyl(vote) %>%
  arrange(desc(n)) %>%
  adorn_totals("row") %>%
  adorn_pct_formatting(rounding = "half up", digits = 0) %>%
  kable(col.names = c('Voto', '#', 'Porcentaje'),
               align = c('ccc')) %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE, 
                                      position = "float_left")

```


```{r viz-vote, echo=FALSE, fig.height=5, fig.width=5, fig.align='right'}
ggplot(freq_vote, aes(x = "", y = percentage_voto, fill = vote)) +
  geom_bar(stat="identity", width=2, color="white") +
  coord_polar("y", start=0) +
  theme_void() + 
  theme(legend.position = "right") +
  guides(fill=guide_legend(title=NULL)) +
  scale_fill_manual(values=c("#4daf4a", "#e41a1c", "#CCCCCC"), 
                    breaks=c("A favor", "En contra", "Abstención")) 
```







 

