---
title: "notas"
author: "Ariadna Chuaqui"
date: "10/1/2020"
output: html_document
---

### Resultados Votación

```{r table-vote, echo=FALSE, fig.align='center'}
votos %>%
  tabyl(vote) %>%
  arrange(desc(n)) %>%
  adorn_totals("row") %>%
  adorn_pct_formatting(rounding = "half up", digits = 0) %>%
  kable(col.names = c('Voto', '#', 'Porcentaje'),
               align = c('ccc')) %>%
  kable_styling(bootstrap_options = "striped", full_width = FALSE, 
                                      position = "center")

```




### Comentarios positivos

```{r box-pos-com}
articles <- computeArticles()
valueBox(articles, icon = "fa-pencil")
```

### Comentarios negativos

```{r box-neg-com}
spam <- computeSpam()
valueBox(spam, 
         icon = "fa-trash",
         color = ifelse(spam > 10, "warning", "primary"))
```


### Comentarios con Sentimiento Positivo {.value-box}

```{r box-com-pos}
comments %>%
  count(buen_comentario = "Si") %>%
  valueBox(icon = "fa-thumbs-up", color = "#b2df8a")  
```

### Comentarios con Sentimiento Negativo {.value-box}

```{r box-com-neg}
comments %>%
  count(buen_comentario = "No") %>%
  valueBox(icon = "fa-thumbs-down", color = "#fb9a99")
```

  ggsave("CC2.html", vizregion, width = 10, height = 20)
